//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CompanyManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transaction
    {
        public int id { get; set; }
        public Nullable<int> product_id { get; set; }
        public Nullable<System.DateTime> move_date { get; set; }
        public string order_id { get; set; }
        public Nullable<double> balance { get; set; }
        public Nullable<double> income { get; set; }
        public Nullable<double> outcome { get; set; }
        public Nullable<decimal> sale_price { get; set; }
    
        public virtual Order Order { get; set; }
        public virtual Product Product { get; set; }
    }
}
