//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CompanyManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UoMCategory
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public UoMCategory()
        {
            this.Unit_of_Measures = new HashSet<Unit_of_Measures>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
        public Nullable<bool> refranse_flag { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Unit_of_Measures> Unit_of_Measures { get; set; }
    }
}
